const blocks = {
  pid: 'play_id',
  blk: 'blocker',
  brcv: 'recovering_player',
  type: 'type',
};

const chart = {
  gid: 'id_game', 
  pid: 'id_play', 
  detail: 'play_text', 
  off: 'team_on_offense', 
  def: 'team_on_defense', 
  type: 'play_type', 
  qb: 'quarterback', 
  trg: 'pass_target', 
  bc: 'ball_carrier', 
  qtr: 'quarter', 
  los: 'line_of_scrimmage', 
  dwn: 'down', 
  ytg: 'yards_to_go', 
  yfog: 'yards_from_own_goal', 
  zone: 'field_zone', 
  yds: 'yardage', 
  succ: 'successful_play', 
  fd: 'first_down', 
  sg: 'shotgun', 
  nh: 'no_huddle', 
  comp: 'completion', 
  ints: 'interception', 
  back: 'players_in_backfield', 
  xlm: 'extra_men_on_line', 
  psmot: 'pre_snap_motion', 
  box: 'defenders_in_box', 
  boxdb: 'dbs_in_box', 
  pap: 'play_action_pass', 
  trick: 'trick_play', 
  qbp: 'quarterback_pressured', 
  qbhi: 'quarterback_hit', 
  qbhu: 'quarterback_hurried', 
  qbru: 'quarterback_run', 
  sneak: 'quarterback_sneak', 
  scrm: 'quarterback_scramble', 
  ttscrm: 'time_to_scramble',  
  htm: 'throw_motion_hindered', 
  pru: 'pass_rushers', 
  blz: 'total_blitzers', 
  dblz: 'db_blitzers', 
  spru: 'stunt_pass_rushers', 
  oop: 'out_of_pocket_pass', 
  oopd: 'out_of_pocket_pass_detail', 
  avt: 'available_targets', 
  dotr: 'depth_of_target_rank', 
  cov: 'coverage_of_target', 
  phyb: 'physical_ball', 
  cnb: 'contested_ball', 
  cball: 'catchable_ball', 
  uball: 'uncatchable_ball', 
  shov: 'shovel_pass', 
  side: 'sideline_pass', 
  high: 'highlight_pass', 
  crr: 'created_reception', 
  intw: 'interception_worthy', 
  drp: 'dropped_pass', 
  avsck: 'avoided_sacks', 
  fread: 'first_read', 
  scre: 'screen_pass', 
  pfp: 'pain_free_play', 
  mbt: 'missed_broken_tackles', 
  ttsk: 'time_to_sack', 
  ttpr: 'time_to_pressue', 
  tay: 'true_air_yards', 
  dot: 'depth_of_target', 
  yac: 'yards_after_catch', 
  yaco: 'yards_after_contact', 
  ytru: 'yards_trucking', 
  covdis1: 'coverage_distance_primary', 
  covdis2: 'coverage_distance_secondary', 
  defpr1: 'pressure_defender_primary', 
  defpr2: 'pressure_defender_secondary', 
  defhi: 'defender_code', 
  defhu1: 'hurry_defender_primary', 
  defhu2: 'hurry_defender_secondary',
};

const conversions = {
  pid: 'play_id',
  type: 'play_type',
  bc: 'ball_carrier',
  psr: 'passer',
  trg: 'pass_target',
  conv: 'coverted',
};

const defense = {
  uid: 'uuid',
  gid: 'game_id',
  player: 'player',
  solo: 'solo_tackles',
  comb: 'combined_tackles',
  sck: 'sacks',
  saf: 'safeties',
  blk: 'blocked_kicks',
  ints: 'interceptions',
  pdef: 'passes_defended',
  frcv: 'fumbles_recovered',
  forc: 'fumbles_forced',
  tdd: 'touchdowns',
  rety: 'return_yardage',
  tdret: 'return_touchdowns',
  peny: 'penalty_yardage',
  snp: 'snaps',
  fp: 'fantasy_points_nfl',
  fp2: 'fantasy_points_fd_dk',
  game: 'player_game',
  seas: 'seasons_played',
  year: 'nfl_season',
  team: 'team',
  posd: 'position_depth_chart',
  jnum: 'jersey_number',
  dcp: 'depth_chart',
  nflid: 'nfl_player_id',
};

const drives = {
  uid: 'uuid', 
  gid: 'game_id', 
  fpid: 'first_play_id', 
  tname: 'team', 
  drvn: 'drive_number', 
  obt: 'how_obtained', 
  qtr: 'quarter', 
  min: 'minutes', 
  sec: 'seconds', 
  yfog: 'starting_field_position', 
  plays: 'plays', 
  succ: 'successful_plays', 
  rfd: 'rushing_first_downs', 
  pfd: 'passing_first_downs', 
  ofd: 'other_first_downs', 
  ry: 'rushing_yardage', 
  ra: 'rushing_attempts', 
  py: 'passing_yardage', 
  pa: 'passing_attempts', 
  pc: 'passing_completions', 
  peyf: 'penalty_yardage_for', 
  peya: 'penalty_yardage_against', 
  net: 'net_yardage', 
  res: 'result',
};

const fieldGoalsExtraPoints = {
  pid: 'id_play', 
  fgxp: 'type', 
  fkicker: 'kicker', 
  dist: 'distance', 
  good: 'was_made',
};

const headers = {
  'BLOCK.csv': blocks,
  'CHART.csv': chart,
  'CONV.csv': conversions,
  'DEFENSE.csv': defense,
  'DRIVE.csv': drives,
  'FGXP.csv': fieldGoalsExtraPoints,
};

export { headers };
