apiVersion: skaffold/v2beta5
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: scostello/pfv-api
      context: ./packages/pfv-api
      docker:
        dockerfile: Dockerfile
        target: debug
      sync:
        manual:
          # Sync all the javascript files that are in the src folder
          # with the container src folder
          - src: 'src/**/*.ts'
            dest: .
deploy:
  helm:
    releases:
      - name: nginx-ingress
        chartPath: stable/nginx-ingress
        version: 1.33.5
        remote: true
        setValues:
          defaultBackend.enabled: false
          controller.hostNetwork: true
          controller.dnsPolicy: "ClusterFirstWithHostNet"
          rbac.create: true
      - name: pfv-api
        chartPath: ./packages/pfv-api/helm-chart
        artifactOverrides:
          image: scostello/pfv-api
        setValues:
          imagePullPolicy: Never