CREATE TABLE IF NOT EXISTS armchair_analysis.play_by_play (
	game_id                       integer,
	play_id                       integer,
	play_text                     varchar,
	team_on_offense               varchar,
	team_on_defense               varchar,
	play_type                     varchar,
	drive_sequence_number         varchar,
	play_duration                 varchar,
	quarter                       varchar,
	minutes                       varchar,
	seconds                       varchar,
	points_offense                varchar,
	points_defense                varchar,
	timeouts_offense              varchar,
	timeouts_defense              varchar,
	down                          varchar,
	yards_to_go                   varchar,
	yards_from_own_goal           varchar,
	field_zone                    varchar,
	yardage                       varchar,
	successful_play               boolean,
	first_down                    boolean,
	shotgun                       boolean,
	no_huddle                     boolean,
	points_scored                 boolean,
	ball_carrier                  varchar,
	took_knee                     boolean,
	rush_direction                varchar,
	rush_tackler_primary          varchar,
	rush_tackler_seconday         varchar,
	passer                        varchar,
	completion                    boolean,
	spiked_ball                   boolean,
	pass_location                 varchar,
	pass_target                   varchar,
	pass_defender                 varchar,
	pass_tackler_primary          varchar,
	pass_tackler_secondary        varchar,
	sacking_player_primary        varchar,
	sacking_player_secondary      varchar,
	penalty_team_primary          varchar,
	penalty_player_primary        varchar,
	penalty_description_primary   varchar,
	penalty_category_primary      varchar,
	penalty_yards_primary         varchar,
	penalty_action_primary        varchar,
	penalty_team_secondary        varchar,
	penalty_player_secondary      varchar,
	penalty_description_secondary varchar,
	penalty_category_secondary    varchar,
	penalty_yards_secondary       varchar,
	penalty_action_secondary      varchar,
	penalty_team_tertiary         varchar,
	penalty_player_tertiary       varchar,
	penalty_description_tertiary  varchar,
	penalty_category_tertiary     varchar,
	penalty_yards_tertiary        varchar,
	penalty_action_tertiary       varchar,
  intercepting_player           varchar,
  interception_return_yardage   varchar,
	fumbler                       varchar,
	fumble_recoverer              varchar,
	fumble_return_yardage         int    ,
	fumble_forcer                 varchar,
	fumble_lost                   boolean,
	safety_player                 varchar,
	kick_blocker                  varchar,
	kick_block_recoverer          varchar,
	kick_type                     varchar,
	kicker                        varchar,
	kick_distance                 int    ,
	kick_made                     boolean,
	punter                        varchar,
	punt_gross                    int    ,
	punt_net                      int    ,
	punt_touchback                boolean,
	punt_returner                 varchar,
	punt_return_yardage           int    ,
	fair_catch                    boolean,
	kicker                        varchar,
	kick_gross                    int    ,
	kick_net                      int    ,
	kick_touchback                boolean,
	kick_returner                 varchar,
	kick_return_yardage           int    ,
);