CREATE TABLE IF NOT EXISTS armchair_analysis.players (
	player_id            varchar,
	first_name           varchar,
	last_name            varchar,
	play_by_play_name    varchar,
	position_1           varchar,
	position_2           varchar,
	height               smallint,
	weight               integer,
	date_of_birth        date,
	forty                numeric,
	bench                smallint,
	vertical             numeric,
	broad                integer,
	shuttle              numeric,
	cone                 numeric,
	arm_length           numeric,
	hand_size            numeric,
	draft_position       integer,
	college              varchar,
	college_division     varchar,
	first_year           integer,
	current_team         varchar,
	position_depth_chart varchar,
	jersey_number        smallint,
	depth_chart          smallint,
	nfl_player_id        varchar,
);

COPY players
FROM '/tmp/nfl_00-18/PLAYER.csv' DELIMITER ',' CSV HEADER;