CREATE TABLE IF NOT EXISTS reporting.drives (
	uuid                    bigint PRIMARY KEY NOT NULL DEFAULT public.id_generator(),
	id_game                 bigint,
	id_first_play           bigint,
	team                    varchar(3),
	drive_number            smallint,
	how_obtained            varchar(4),
	quarter                 smallint,
	minutes                 smallint,
	seconds                 smallint,
	starting_field_position smallint,
	plays                   smallint,
	successful_plays        smallint,
	rushing_first_downs     smallint,
	passing_first_downs     smallint,
	other_first_downs       smallint,
	rushing_attempts        smallint,
	rushing_yardage         integer,
	passing_attempts        smallint,
	passing_completions     smallint,
	passing_yardage         integer,
	penalty_yardage_for     smallint,
	penalty_yardage_against smallint,
	net_yardage             integer,
	result                  varchar(4)
);