import * as R from 'ramda';

const toNumber = (value: any) => Number(value);

const bitToBoolean = (value: 0 | 1): boolean => value !== 0;

const isEmptyString = R.both(R.is(String), R.isEmpty);

const nullifyEmpty = R.ifElse(
  isEmptyString,
  R.always(null),
  R.identity,
);

const toBoolean = R.ifElse(
  isEmptyString,
  R.always(null),
  R.compose(bitToBoolean, toNumber),
);

type HeaderMap = { [columnName: string]: string | { name: string; transform?: (value: any) => any } };

interface CsvMappable {
  mapValues: (args: { header: string, value: any }) => any;
  mapHeaders: (args: { header: string }) => string;
}

class MappedTable implements CsvMappable {
  private _batchSize: number;

  private _tableName: string;

  private _headerMap: HeaderMap;

  private _newHeaders = {};

  constructor(tableName: string, headerMap: HeaderMap, batchSize: number = 750) {
    this._tableName = tableName;
    this._headerMap = headerMap;
    this._batchSize = batchSize;
  }

  get batchSize() {
    return this._batchSize;
  }

  get tableName() {
    return this._tableName;
  }

  mapValues = ({ header, value }) => {
    const transform = this._newHeaders[header].transform || nullifyEmpty;
    return transform(value);
  }

  mapHeaders = ({ header }) => {
    const newHeader = R.has('name', this._headerMap[header])
      ? R.prop('name', this._headerMap[header])
      : this._headerMap[header];

    const transform = R.has('transform', this._headerMap[header])
      ? R.prop('transform', this._headerMap[header])
      : nullifyEmpty;

    this._newHeaders[newHeader] = {
      transform,
    };

    return newHeader;
  }
}

const blocks = new MappedTable('blocks', {
  pid: 'id_play',
  blk: 'blocker',
  brcv: {
    name: 'recovering_player',
    transform: nullifyEmpty,
  },
  type: 'type',
});

const chart = new MappedTable('chart', {
  gid: 'id_game',
  pid: 'id_play',
  detail: 'play_text',
  off: 'team_on_offense',
  def: 'team_on_defense',
  type: 'play_type',
  qb: 'quarterback',
  trg: 'pass_target',
  bc: 'ball_carrier',
  qtr: 'quarter',
  los: 'line_of_scrimmage',
  dwn: 'down',
  ytg: 'yards_to_go',
  yfog: 'yards_from_own_goal',
  zone: 'field_zone',
  yds: 'yardage',
  succ: {
    name: 'successful_play',
    transform: toBoolean,
  },
  fd: {
    name: 'first_down',
    transform: toBoolean,
  },
  sg: {
    name: 'shotgun',
    transform: toBoolean,
  },
  nh: {
    name: 'no_huddle',
    transform: toBoolean,
  },
  comp: {
    name: 'completion',
    transform: toBoolean,
  },
  ints: {
    name: 'interception',
    transform: toBoolean,
  },
  back: 'players_in_backfield',
  xlm: 'extra_men_on_line',
  psmot: {
    name: 'pre_snap_motion',
    transform: toBoolean,
  },
  box: 'defenders_in_box',
  boxdb: 'dbs_in_box',
  pap: {
    name: 'play_action_pass',
    transform: toBoolean,
  },
  trick: {
    name: 'trick_play',
    transform: toBoolean,
  },
  qbp: {
    name: 'quarterback_pressured',
    transform: toBoolean,
  },
  qbhi: {
    name: 'quarterback_hit',
    transform: toBoolean,
  },
  qbhu: {
    name: 'quarterback_hurried',
    transform: toBoolean,
  },
  qbru: {
    name: 'quarterback_run',
    transform: toBoolean,
  },
  sneak: {
    name: 'quarterback_sneak',
    transform: toBoolean,
  },
  scrm: {
    name: 'quarterback_scramble',
    transform: toBoolean,
  },
  ttscrm: {
    name: 'time_to_scramble',
  },
  htm: {
    name: 'throw_motion_hindered',
    transform: toBoolean,
  },
  pru: 'pass_rushers',
  blz: 'total_blitzers',
  dblz: 'db_blitzers',
  spru: 'stunt_pass_rushers',
  oop: {
    name: 'out_of_pocket_pass',
    transform: toBoolean,
  },
  oopd: 'out_of_pocket_pass_detail',
  avt: 'available_targets',
  dotr: 'depth_of_target_rank',
  cov: 'coverage_of_target',
  phyb: {
    name: 'physical_ball',
    transform: toBoolean,
  },
  cnb: {
    name: 'contested_ball',
    transform: toBoolean,
  },
  cball: {
    name: 'catchable_ball',
    transform: toBoolean,
  },
  uball: {
    name: 'uncatchable_ball',
    transform: toBoolean,
  },
  shov: {
    name: 'shovel_pass',
    transform: toBoolean,
  },
  side: {
    name: 'sideline_pass',
    transform: toBoolean,
  },
  high: {
    name: 'highlight_pass',
    transform: toBoolean,
  },
  crr: {
    name: 'created_reception',
    transform: toBoolean,
  },
  intw: {
    name: 'interception_worthy',
    transform: toBoolean,
  },
  drp: {
    name: 'dropped_pass',
    transform: toBoolean,
  },
  avsck: {
    name: 'avoided_sacks',
    transform: toBoolean,
  },
  fread: {
    name: 'first_read',
    transform: toBoolean,
  },
  scre: {
    name: 'screen_pass',
    transform: toBoolean,
  },
  pfp: {
    name: 'pain_free_play',
    transform: toBoolean,
  },
  mbt: {
    name: 'missed_broken_tackles',
    transform: toBoolean,
  },
  ttsk: 'time_to_sack',
  ttpr: 'time_to_pressure',
  tay: 'true_air_yards',
  dot: 'depth_of_target',
  yac: 'yards_after_catch',
  yaco: 'yards_after_contact',
  ytru: 'yards_trucking',
  covdis1: 'coverage_distance_primary',
  covdis2: 'coverage_distance_secondary',
  defpr1:'pressure_defender_primary',
  defpr2:'pressure_defender_secondary',
  defhi: 'defender_code',
  defhu1:'hurry_defender_primary',
  defhu2:'hurry_defender_secondary',
});

const conversions = new MappedTable('conversions', {
  pid: 'id_play',
  type: 'play_type',
  bc: 'ball_carrier',
  psr: 'passer',
  trg: 'pass_target',
  conv: {
    name: 'converted',
    transform: toBoolean,
  },
});

const defense = new MappedTable('defense', {
  uid: 'uuid',
  gid: 'id_game',
  player: 'player',
  solo: 'solo_tackles',
  comb: 'combined_tackles',
  sck: 'sacks',
  saf: 'safeties',
  blk: 'blocked_kicks',
  ints: 'interceptions',
  pdef: 'passes_defended',
  frcv: 'fumbles_recovered',
  forc: 'fumbles_forced',
  tdd: 'touchdowns',
  rety: 'return_yardage',
  tdret: 'return_touchdowns',
  peny: 'penalty_yardage',
  snp: 'snaps',
  fp: 'fantasy_points_nfl',
  fp2: 'fantasy_points_fd_dk',
  game: 'player_game',
  seas: 'seasons_played',
  year: 'nfl_season',
  team: 'team',
  posd: 'position_depth_chart',
  jnum: 'jersey_number',
  dcp: 'depth_chart',
  nflid: 'nfl_player_id',
});

// const drives = {
//   uid: 'uuid',
//   gid: 'id_game',
//   fpid: 'first_play_id',
//   tname: 'team',
//   drvn: 'drive_number',
//   obt: 'how_obtained',
//   qtr: 'quarter',
//   min: 'minutes',
//   sec: 'seconds',
//   yfog: 'starting_field_position',
//   plays: 'plays',
//   succ: 'successful_plays',
//   rfd: 'rushing_first_downs',
//   pfd: 'passing_first_downs',
//   ofd: 'other_first_downs',
//   ry: 'rushing_yardage',
//   ra: 'rushing_attempts',
//   py: 'passing_yardage',
//   pa: 'passing_attempts',
//   pc: 'passing_completions',
//   peyf: 'penalty_yardage_for',
//   peya: 'penalty_yardage_against',
//   net: 'net_yardage',
//   res: 'result',
// };

// const fieldGoalsExtraPoints = {
//   pid: 'id_play',
//   fgxp: 'type',
//   fkicker: 'kicker',
//   dist: 'distance',
//   good: 'was_made',
// };

// const fumbles = {
//   pid: 'id_play',
//   fum: 'fumbler',
//   frcv: 'recovering_player',
//   fry: 'return_yardage',
//   forc: 'forcing_player',
//   fuml: 'fumble_lost',
// };

// const games = {
//   gid: 'id_game',
//   seas: 'season',
//   wk: 'week',
//   day: 'day',
//   v: 'visiting_team',
//   h: 'home_team',
//   stad: 'stadium',
//   temp: 'temperature',
//   humd: 'humidity',
//   wspd: 'wind_speed',
//   wdir: 'wind_direction',
//   cond: 'conditions',
//   surf: 'surface',
//   ou: 'over_under',
//   sprv: 'vis_point_spread',
//   ptsv: 'points_visitor',
//   ptsh: 'points_home',
// }

// const injuries = {
//   uid: 'uuid',
//   gid: 'id_game',
//   player: 'player',
//   team: 'team',
//   details: 'details',
//   pstat: 'practice_status',
//   gstat: 'game_status',
// };

// const interceptions = {
//   pid: 'id_play',
//   psr: 'passer',
//   ints: 'interceptor',
//   iry: 'return_yardage',
// };

// const kickers = {
//   uid: 'uuid',
//   gid: 'id_game',
//   player: 'player',
//   pat: 'pats',
//   fgs: 'field_goals_short',
//   fgm: 'field_goals_med',
//   fgl: 'field_goals_long',
//   fp: 'fantasy_points',
//   game: 'player_game_number',
//   seas: 'seasons_played',
//   year: 'year',
//   team: 'team',
// };

// const kickoffs = {
//   pid: 'id_play',
//   kicker: 'kicker',
//   kgro: 'gross_yardage',
//   knet: 'net_yardage',
//   ktb: 'touchback',
//   kr: 'returner',
//   kry: 'return_yardage',
// };

// const offense = {
//   uid: 'uuid',
//   gid: 'id_game',
//   player: 'player',
//   pa: 'passing_attempts',
//   pc: 'passing_completions',
//   py: 'passing_yardage',
//   ints: 'interceptions',
//   tdp: 'passing_touchdowns',
//   ra: 'rushing_attempts',
//   sra: 'successful_rushing_attempts',
//   ry: 'rushing_yardage',
//   tdr: 'rushing_touchdowns',
//   trg: 'times_targeted',
//   rec: 'receptions',
//   recy: 'receiving_yardage',
//   tdrec: 'receiving_touchdowns',
//   ret: 'returns',
//   rety: 'return_yardage',
//   tdret: 'return_touchdowns',
//   fuml: 'fumbles_lost',
//   peny: 'penalty_yardage',
//   conv: 'conversion',
//   snp: 'snaps',
//   fp: 'fantasy_points_nfl',
//   fp2: 'fantasy_points_fd',
//   fp3: 'fantasy_points_dk',
//   game: 'player_game_number',
//   seas: 'seasons_played',
//   year: 'year',
//   team: 'team',
//   posd: 'position_depth_chart',
//   jnum: 'jersey_number',
//   dcp: 'depth_chart',
//   nflid: 'nfl_player_id',
// };

// const passing = {
//   pid: 'id_play',
//   psr: 'passer',
//   trg: 'target',
//   loc: 'location',
//   yds: 'yards',
//   comp: 'completed',
//   succ: 'successful_play',
//   spk: 'spiked_ball',
//   dfb: 'defender',
// };

// const playByPlay = {
//   gid: 'id_game',
//   pid: 'id_play',
//   detail: 'play_text',
//   off: 'team_on_offense',
//   def: 'team_on_defense',
//   type: 'play_type',
//   dseq: 'drive_sequence_number',
//   len: 'play_duration',
//   qtr: 'quarter',
//   min: 'minutes',
//   sec: 'seconds',
//   ptso: 'points_offense',
//   ptsd: 'points_defense',
//   timo: 'timeouts_offense',
//   timd: 'timeouts_defense',
//   dwn: 'down',
//   ytg: 'yards_to_go',
//   yfog: 'yards_from_own_goal',
//   zone: 'field_zone',
//   yds: 'yardage',
//   succ: 'successful_play',
//   fd: 'first_down',
//   sg: 'shotgun',
//   nh: 'no_huddle',
//   pts: 'points_scored',
//   bc: 'ball_carrier',
//   kne: 'took_knee',
//   dir: 'rush_direction',
//   rtck1: 'rush_tackler_primary',
//   rtck2: 'rush_tackler_seconday',
//   psr: 'passer',
//   comp: 'completion',
//   spk: 'spiked_ball',
//   loc: 'pass_location',
//   trg: 'pass_target',
//   dfb: 'pass_defender',
//   ptck1: 'pass_tackler_primary',
//   ptck2: 'pass_tackler_secondary',
//   sk1: 'sacking_player_primary',
//   sk2: 'sacking_player_secondary',
//   ptm1: 'penalty_team_primary',
//   pen1: 'penalty_player_primary',
//   desc1: 'penalty_description_primary',
//   cat1: 'penalty_category_primary',
//   pey1: 'penalty_yards_primary',
//   act1: 'penalty_action_primary',
//   ptm2: 'penalty_team_secondary',
//   pen2: 'penalty_player_secondary',
//   desc2: 'penalty_description_secondary',
//   cat2: 'penalty_category_secondary',
//   pey2: 'penalty_yards_secondary',
//   act2: 'penalty_action_secondary',
//   ptm3: 'penalty_team_tertiary',
//   pen3: 'penalty_player_tertiary',
//   desc3: 'penalty_description_tertiary',
//   cat3: 'penalty_category_tertiary',
//   pey3: 'penalty_yards_tertiary',
//   act3: 'penalty_action_tertiary',
//   ints: 'intercepting_player',
//   iry: 'interception_return_yardage',
//   fum: 'fumbler',
//   frcv: 'fumble_recoverer',
//   fry: 'fumble_return_yardage',
//   forc: 'fumble_forcer',
//   fuml: 'fumble_lost',
//   saf: 'safety_player',
//   blk: 'kick_blocker',
//   brcv: 'kick_block_recoverer',
//   fgxp: 'kick_type',
//   fkicker: 'kicker',
//   dist: 'kick_distance',
//   good: 'kick_made',
//   punter: 'punter',
//   pgro: 'punt_gross',
//   pnet: 'punt_net',
//   ptb: 'punt_touchback',
//   pr: 'punt_returner',
//   pry: 'punt_return_yardage',
//   pfc: 'fair_catch',
//   kicker: 'kicker',
//   kgro: 'kick_gross',
//   knet: 'kick_net',
//   ktb: 'kick_touchback',
//   kr: 'kick_returner',
//   kry: 'kick_return_yardage',
// };

// const penalties = {
//   uid: 'uuid',
//   pid: 'id_play',
//   ptm: 'flagged_team',
//   pen: 'flagged_player',
//   desc: 'description',
//   cat: 'category',
//   pey: 'assessed_yardage',
//   act: 'action',
// };

// const plays = {
//   gid: 'id_game',
//   pid: 'id_play',
//   off: 'team_on_offense',
//   def: 'team_on_defense',
//   type: 'play_type',
//   dseq: 'drive_sequence',
//   len: 'length_in_seconds',
//   qtr: 'quarter',
//   min: 'minutes',
//   sec: 'seconds',
//   ptso: 'points_offense',
//   ptsd: 'points_defense',
//   timo: 'timeouts_offense',
//   timd: 'timeouts_defense',
//   dwn: 'down',
//   ytg: 'yards_to_go',
//   yfog: 'yards_from_own_goaline',
//   zone: 'field_zone',
//   fd: 'first_down',
//   sg: 'shotgun',
//   nh: 'no_huddle',
//   pts: 'points_scored',
//   tck: 'tackle_on_play',
//   sk: 'sack_on_play',
//   pen: 'penalty_on_play',
//   ints: 'interception_on_play',
//   fum: 'fumble_on_play',
//   saf: 'safety_on_play',
//   blk: 'block_on_play',  
// };

// const players = {
//   player: 'player_id',
//   fname: 'first_name',
//   lname: 'last_name',
//   pname: 'play_by_play_name',
//   pos1: 'position_1',
//   pos2: 'position_2',
//   height: 'height',
//   weight: 'weight',
//   dob: 'date_of_birth',
//   forty: 'forty',
//   bench: 'bench',
//   vertical: 'vertical',
//   broad: 'broad',
//   shuttle: 'shuttle',
//   cone: 'cone',
//   arm: 'arm_length',
//   hand: 'hand_size',
//   dpos: 'draft_position',
//   col: 'college',
//   dv: 'college_division',
//   start: 'first_year',
//   cteam: 'current_team',
//   posd: 'position_depth_chart',
//   jnum: 'jersey_number',
//   dcp: 'depth_chart',
//   nflid: 'nfl_player_id',
// };

// const punts = {
//   pid: 'id_play',
//   punter: 'punter',
//   pgro: 'gross_yardage',
//   pnet: 'net_yardage',
//   ptb: 'touchback',
//   pr: 'returner',
//   pry: 'return_yardage',
//   pfc: 'fair_caught',
// };

// const redzone = {
//   uid: 'uuid',
//   gid: 'id_game',
//   player: 'player',
//   pa: 'passing_attempts',
//   pc: 'passing_completions',
//   py: 'passing_yardage',
//   ints: 'interceptions',
//   ra: 'rushing_attempts',
//   sra: 'successful_rushing_attempts',
//   ry: 'rushing_yardage',
//   trg: 'times_targeted',
//   rec: 'receptions',
//   recy: 'receiving_yardage',
//   fuml: 'fumbles_lost',
//   peny: 'penalty_yardage',
// };

// const rushes = {
//   pid: 'id_play',
//   bc: 'ball_carrier',
//   dir: 'rush_direction',
//   yds: 'yards_gained',
//   succ: 'successful_play',
//   kne: 'kneel_down',
// };

// const sacks = {
//   uid: 'uuid',
//   pid: 'id_play',
//   qb: 'quarter_back',
//   sk: 'sacking_player',
//   value: 'value',
//   ydsl: 'yards_lost',
// };

// const safeties = {
//   pid: 'id_play',
//   saf: 'defender',
// };

// const schedule = {
//   gid: 'id_game',
//   seas: 'season',
//   wk: 'week',
//   day: 'day',
//   date: 'date',
//   v: 'visitor',
//   h: 'home',
//   stad: 'stadium',
//   surf: 'surface',
// };

// const snaps = {
//   uid: 'uuid',
//   gid: 'id_game',
//   tname: 'team',
//   player: 'player',
//   posd: 'position_depth_chart',
//   poss: 'position_starting',
//   snp: 'snaps',
// };

// const tackles = {
//   uid: 'uuid',
//   pid: 'id_play',
//   tck: 'tackler',
//   value: 'value',
// };

// const touchdowns = {
//   pid: 'id_play',
//   qtr: 'quarter',
//   min: 'minutes',
//   sec: 'seconds',
//   dwn: 'down',
//   yds: 'yards',
//   pts: 'points',
//   player: 'scoring_player',
//   type: 'type',  
// };

// const teamTotals = {
//   tid: 'team_total_id',
//   gid: 'id_game',
//   tname: 'team_name',
//   pts: 'points',
//   q1p: 'points_quarter_one',
//   q2p: 'points_quarter_two',
//   q3p: 'points_quarter_three',
//   q4p: 'points_quarter_four',
//   rfd: 'first_downs_rushing',
//   pfd: 'first_downs_passing',
//   ifd: 'first_downs_penalty',
//   ry: 'rushing_yardage',
//   ra: 'rushing_attempts',
//   py: 'passing_yardage',
//   pa: 'passing_attempts',
//   pc: 'passing_completions',
//   sk: 'sacks_against',
//   ints: 'interceptions',
//   fum: 'fumbles_lost',
//   pu: 'punts',
//   gpy: 'gross_punt_yardage',
//   pr: 'punt_returns',
//   pry: 'punt_return_yardage',
//   kr: 'kickoff_returns',
//   kry: 'kickoff_return_yardage',
//   ir: 'interception_returns',
//   iry: 'interception_return_yardage',
//   pen: 'penalty_yardage_against',
//   top: 'time_of_possession',
//   td: 'touchdowns',
//   tdr: 'rushing_touchdowns',
//   tdp: 'passing_touchdowns',
//   tdt: 'turnover_touchdowns',
//   fgm: 'field_goals_made',
//   fgat: 'field_goal_attempts',
//   fgy: 'field_goal_yardage',
//   rza: 'redzone_drives',
//   rzc: 'redzone_touchdowns',
//   bry: 'big_rush_yardage',
//   bpy: 'big_pass_yardage',
//   srp: 'successful_rush_plays',
//   s1rp: 'successful_rush_firstdown',
//   s2rp: 'successful_rush_seconddown',
//   s3rp: 'successful_rush_thirddownplus',
//   spp: 'successful_pass_plays',
//   s1pp: 'successful_pass_firstdown',
//   s2pp: 'successful_pass_seconddown',
//   s3pp: 'successful_pass_thirddownplus',
//   lea: 'rushing_attempts_leftend',
//   ley: 'rushing_yardage_leftend',
//   lta: 'rushing_attempts_lefttackle',
//   lty: 'rushing_yardage_lefttackle',
//   lga: 'rushing_attempts_leftguard',
//   lgy: 'rushing_yardage_leftguard',
//   mda: 'rushing_attempts_middle',
//   mdy: 'rushing_yardage_middle',
//   rga: 'rushing_attempts_rightguard',
//   rgy: 'rushing_yardage_rightguard',
//   rta: 'rushing_attempts_righttackle',
//   rty: 'rushing_yardage_righttackle',
//   rea: 'rushing_attempts_rightend',
//   rey: 'rushing_yardage_rightend',
//   r1a: 'rushing_attempts_firstdown',
//   r1y: 'rushing_yardage_firstdown',
//   r2a: 'rushing_attempts_seconddown',
//   r2y: 'rushing_yardage_seconddown',
//   r3a: 'rushing_attempts_thirddownplus',
//   r3y: 'rushing_yardage_thirddownplus',
//   qba: 'rushing_attempts_quarterback',
//   qby: 'rushing_yardage_quarterback',
//   sla: 'passing_attempts_shortleft',
//   sly: 'passing_yardage_shortleft',
//   sma: 'passing_attempts_shortmiddle',
//   smy: 'passing_yardage_shortmiddle',
//   sra: 'passing_attempts_shortright',
//   sry: 'passing_yardage_shortright',
//   dla: 'passing_attempts_deepleft',
//   dly: 'passing_yardage_deepleft',
//   dma: 'passing_attempts_deepmedium',
//   dmy: 'passing_yardage_deepmedium',
//   dra: 'passing_attempts_deepright',
//   dry: 'passing_yardage_deepright',
//   wr1a: 'passing_attempts_wr1_2',
//   wr1y: 'passing_yardage_wr1_2',
//   wr3a: 'passing_attempts_wr3_4_5',
//   wr3y: 'passing_yardage_wr3_4_5',
//   tea: 'passing_attempts_tightend',
//   tey: 'passing_yardage_tightend',
//   rba: 'passing_attempts_runningback',
//   rby: 'passing_yardage_runningback',
//   sga: 'passing_shotgun_attempts',
//   sgy: 'passing_shotgun_yardage',
//   p1a: 'passing_attempts_firstdown',
//   p1y: 'passing_yardage_firstdown',
//   p2a: 'passing_attempts_seconddown',
//   p2y: 'passing_yardage_seconddown',
//   p3a: 'passing_attempts_thirddownplus',
//   p3y: 'passing_yardage_thirddownplus',
//   spc: 'passing_completions_short',
//   mpc: 'passing_completions_medium',
//   lpc: 'passing_completions_long',
//   q1ra: 'rushing_attempts_quarter_one',
//   q1ry: 'rushing_yardage_quarter_one',
//   q1pa: 'passing_attempts_quarter_one',
//   q1py: 'passing_yardage_quarter_one',
//   lcra: 'rushing_attempts_lateclose',
//   lcry: 'rushing_yardage_lateclose',
//   lcpa: 'passing_attempts_lateclose',
//   lcpy: 'passing_yardage_lateclose',
//   rzra: 'rushing_attempts_redzone',
//   rzry: 'rushing_yardage_redzone',
//   rzpa: 'passing_attempts_redzone',
//   rzpy: 'passing_yardage_redzone',
//   sky: 'yardage_lost_to_sacks',
//   lbs: 'sacks_by_lbs',
//   dbs: 'sacks_by_dbs',
//   sfpy: 'starting_field_position',
//   drv: 'drives_on_offense',
//   npy: 'net_punt_yardage',
//   tb: 'touchbacks',
//   i20: 'punts_inside_20',
//   rtd: 'return_touchdowns',
//   lnr: 'rushing_tackles_defensiveline',
//   lnp: 'passing_tackles_defensiveline',
//   lbr: 'rushing_tackles_linebackers',
//   lbp: 'passing_tackles_linebackers',
//   dbr: 'rushing_tackles_defensivebacks',
//   dbp: 'passing_tackles_defensivebacks',
//   nha: 'no_huddle_attempts',
//   s3a: 'third_and_short_attempts',
//   s3c: 'third_and_short_conversions',
//   l3a: 'third_and_long_attempts',
//   l3c: 'third_and_long_conversions',
//   stf: 'stuffed_runs',
//   dp: 'points_by_defense',
//   fsp: 'false_starts',
//   ohp: 'penalty_offensive_holds',
//   pbep: 'penalty_playbook_execution',
//   dlp: 'penalty_defensive_line',
//   dsp: 'penalty_defensive_secondary',
//   dum: 'penalty_dumb',
//   pfn: 'poor_fundamental',
//   snpo: 'snaps_on_offense',
//   snpd: 'snaps_on_defense',
//   saf: 'safeties_own_defense',
//   blk: 'blocks_own_defense',
//   fp: 'defense_st_points',
//   back0p: 'zero_in_backfield_pass_attempts',
//   back0py: 'zero_in_backfield_pass_yardage',
//   back1p: 'one_in_backfield_pass_attempts',
//   back1py: 'one_in_backfield_pass_yardage',
//   back1r: 'one_in_backfield_rush_attempts',
//   back1ry: 'one_in_backfield_rush_yardage',
//   back2p: 'two_in_backfield_pass_attempts',
//   back2py: 'two_in_backfield_pass_yardage',
//   back2r: 'two_in_backfield_rush_attempts',
//   back2ry: 'two_in_backfield_rush_attempts',
//   back3r: 'threeplus_in_backfield_rush_yardage',
//   back3ry: 'threeplus_in_backfield_rush_yardage',
//   box4p: 'men_in_box_4_pass_attempts',
//   box4py: 'men_in_box_4_pass_yardage',
//   box5p: 'men_in_box_5_pass_attempts',
//   box5py: 'men_in_box_5_pass_yardage',
//   box6p: 'men_in_box_6_pass_attempts',
//   box6py: 'men_in_box_6_pass_yardage',
//   box6r: 'men_in_box_6_rush_attempts',
//   box6ry: 'men_in_box_6_rush_yardage',
//   box7p: 'men_in_box_7_pass_attempts',
//   box7py: 'men_in_box_7_pass_yardage',
//   box7r: 'men_in_box_7_rush_attempts',
//   box7ry: 'men_in_box_7_rush_yardage',
//   box8r: 'men_in_box_8plus_rush_attempts',
//   box8ry: 'men_in_box_8plus_rush_yardage',
//   pap: 'play_action_pass_attempts',
//   papy: 'play_action_pass_yardage',
//   npr: 'qb_pressure_none_attempts',
//   npry: 'qb_pressure_none_yardage',
//   qbp: 'qb_pressure_attempts',
//   qbpy: 'qb_pressure_yardage',
//   qbhi: 'qb_hit_attempts',
//   qbhiy: 'qb_hit_yardage',
//   qbhu: 'qb_hurry_attempts',
//   qbhuy: 'qb_hurry_yardage',
//   scrm: 'qb_scrambles_attempts',
//   scrmy: 'qb_scrambles_yardage',
//   ttscrm: 'time_to_scramble',
//   ttpr: 'time_to_pressure',
//   ttsk: 'time_to_sack',
//   pru3: 'pass_rushers_3_attempts',
//   pru3y: 'pass_rushers_3_yardage',
//   pru4: 'pass_rushers_4_attempts',
//   pru4y: 'pass_rushers_4_yardage',
//   pru5: 'pass_rushers_5_attempts',
//   pru5y: 'pass_rushers_5_yardage',
//   pru6: 'pass_rushers_6plus_attempts',
//   pru6y: 'pass_rushers_6plus_yardage',
//   blz0p: 'blitzers_none_attempts',
//   blz0py: 'blitzers_none_yardage',
//   blz1: 'blitzers_1_attempts',
//   blz1y: 'blitzers_1_yardage',
//   blz2: 'blitzers_2plus_attempts',
//   blz2y: 'blitzers_2plus_yardage',
//   dblz1: 'blitzers_db_1_attempts',
//   dblz1y: 'blitzers_db_1_yardage',
//   spru1: 'pass_rusher_stunt_1_attempts',
//   spru1y: 'pass_rusher_stunt_1_yardage',
//   oopdes: 'out_of_pocket_pass_designed_attempts',
//   oopdesy: 'out_of_pocket_pass_designed_yardage',
//   ooppr: 'out_of_pocket_pass_pressured_attempts',
//   ooppry: 'out_of_pocket_pass_pressured_yardage',
//   oopcl: 'out_of_pocket_pass_cleanpocket_attempts',
//   oopcly: 'out_of_pocket_pass_cleanpocket_yardage',
//   ytg1: 'total_yards_to_go_first',
//   ytg2: 'total_yards_to_go_second',
//   ytg3: 'total_yards_to_go_thirdplus',
//   pc1: 'pass_completions_first',
//   pc2: 'pass_completions_second',
//   pc3: 'pass_completions_thirdplus',
//   tay1: 'total_true_air_yards_first',
//   tay2: 'total_true_air_yards_second',
//   tay3: 'total_true_air_yards_thirdplus',
//   dot1: 'total_depth_of_target_first',
//   dot2: 'total_depth_of_target_second',
//   dot3: 'total_depth_of_target_thirdplus',
//   yac1: 'total_yards_after_catch_first',
//   yac2: 'total_yards_after_catch_second',
//   yac3: 'total_yards_after_catch_thirdplus',
//   cov0: 'target_not_covered',
//   cov0y: 'target_not_covered_yardage',
//   cov1: 'target_single_coverage',
//   cov1y: 'target_single_coverage_yardage',
//   cov2: 'target_double_covered',
//   cov2y: 'target_double_covered_yardage',
//   drp: 'receiver_drops',
// };

const mappers: { [entryPath: string]: MappedTable } = {
  'BLOCK.csv': blocks,
  'CHART.csv': chart,
  'CONV.csv': conversions,
  'DEFENSE.csv': defense,
  // 'DRIVE.csv': drives,
  // 'FGXP.csv': fieldGoalsExtraPoints,
  // 'FUMBLE.csv': fumbles,
  // 'GAME.csv': games,
  // 'INJURY.csv': injuries,
  // 'INTERCPT.csv': interceptions,
  // 'KICKER.csv': kickers,
  // 'KOFF.csv': kickoffs,
  // 'OFFENSE.csv': offense,
  // 'PASS.csv': passing,
  // 'PBP.csv': playByPlay,
  // 'PENALTY.csv': penalties,
  // 'PLAY.csv': plays,
  // 'PLAYER.csv': players,
  // 'PUNT.csv': punts,
  // 'REDZONE.csv': redzone,
  // 'RUSH.csv': rushes,
  // 'SACK.csv': sacks,
  // 'SAFETY.csv': safeties,
  // 'SCHEDULE.csv': schedule,
  // 'SNAP.csv': snaps,
  // 'TACKLE.csv': tackles,
  // 'TD.csv': touchdowns,
  // 'TEAM.csv': teamTotals,
};

const getMapper = (path: string) => mappers[path];

export { getMapper };
