sudo: required

language: minimal

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin quay.io
  - docker build -t quay.io/sean.costello/pfa-api:latest .

script:
  - docker images