sudo: required

language: node_js
node_js:
  - "12"

services:
  - docker

before_install:
  - sudo apt-get install jq -y
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin quay.io

# All stages, except for the Release stage, utilize a built docker image
# No need to duplicate package installs
install: skip

jobs:
  include:
    - stage: Build Image
      script:
        - docker build -t pfa-api-ci .
        - docker images
        - docker tag pfa-api-ci quay.io/$DOCKER_USERNAME/pfa-api:build-$TRAVIS_BUILD_NUMBER
        - docker push quay.io/$DOCKER_USERNAME/pfa-api:build-$TRAVIS_BUILD_NUMBER
    - stage: Test Image
      script:
        - docker run --rm quay.io/$DOCKER_USERNAME/pfa-api:build-$TRAVIS_BUILD_NUMBER test
    - stage: Release
      script: skip
      node_js: "12"
      deploy:
        provider: script
        skip_cleanup: true
        on:
          branch: master
        script: ./scripts/deploy.sh