#!/usr/bin/env sh

HOSTS_FILE="/etc/hosts"
MINIKUBE_IP=$(minikube ip)
MINIKUBE_HOSTNAME="minikube.test"
MINIKUBE_SUBDOMAINS="api db schema-ui"
PWD=$(pwd)
K8S_DIR=${PWD}/k8s

kubectl config use-context minikube

if [[ $EUID -ne 0 ]]; then
  echo "Please enter your password for 'sudo' - Required to update ${HOSTS_FILE}"
  sudo echo >> /dev/null
fi

if [[ -n "$(grep ${MINIKUBE_HOSTNAME} ${HOSTS_FILE})" ]]; then
  sudo sed -i '' -e "/${MINIKUBE_HOSTNAME}/d" ${HOSTS_FILE}
fi

HOSTS_ENTRY="${MINIKUBE_IP} ${MINIKUBE_HOSTNAME}"
for subdomain in ${MINIKUBE_SUBDOMAINS}; do
  HOSTS_ENTRY="${HOSTS_ENTRY} ${subdomain}.${MINIKUBE_HOSTNAME}"
done

echo "${HOSTS_ENTRY}" | sudo tee -a ${HOSTS_FILE}

install_postgres() {
  release_name="postgresql"
  if [[ -z $(helm ls --filter=${release_name}) ]]; then
      helm uninstall ${release_name}
  fi

  helm install ${release_name} \
    --version "8.6.10" \
    --values ${K8S_DIR}/chart-overrides/pg-values.yaml \
    bitnami/postgresql
}

install_kafka() {
  release_name="kafka"
  if [[ -z $(helm ls --filter=${release_name}) ]]; then
      helm uninstall ${release_name}
  fi

  helm install ${release_name} \
    --version "9.0.4" \
    bitnami/kafka
}

install_schema_registry() {
  release_name="schema-registry"
  if [[ -z $(helm ls --filter=${release_name}) ]]; then
      helm uninstall ${release_name}
  fi

  helm install ${release_name} \
    --version "0.5.0" \
    --values ${K8S_DIR}/chart-overrides/schema-registry-values.yaml \
    confluentinc/cp-helm-charts
     
}

install_kafka_connect() {
  release_name="kafka-connect"
  if [[ -z $(helm ls --filter=${release_name}) ]]; then
      helm uninstall ${release_name}
  fi

  helm install ${release_name} \
    --version "0.5.0" \
    --values ${K8S_DIR}/chart-overrides/kafka-connect-values.yaml \
    confluentinc/cp-helm-charts
     
}

helm repo update
# install_postgres
# install_kafka
# install_schema_registry
# install_kafka_connect

#exec skaffold dev
